name: Main
permissions: write-all
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:  # Allows manual triggering
  watch:
    types: [started]  # Triggers when someone stars the repo

jobs:
  build:
    name: build openwrt for tr3000
    runs-on: ubuntu-latest
    
    # Removed owner restriction - now any star will trigger the build
    # if: github.event_name != 'watch' || github.event.sender.login == github.repository_owner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt update
          sudo -E apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: Clone openwrt source code
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          git branch -a
          git tag
          git checkout v24.10.0
          echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> "feeds.conf.default"
          echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> "feeds.conf.default"

      - name: Update the feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy config file if exists
        run: |
          if [ -f .config ]; then
            cp .config openwrt/
          fi
        
      - name: Run menuconfig (interactive for manual runs)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd openwrt
          make menuconfig
          make defconfig
          
      - name: make download
        env:
          FORCE_UNSAFE_CONFIGURE: 1
        run: |
          cd openwrt
          make defconfig
          make download

      - name: make
        env:
          FORCE_UNSAFE_CONFIGURE: 1
        run: |
          cd openwrt
          make -j$(nproc)

      - name: zip the bin
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r openwrt-tr3000.zip openwrt/bin

      - name: Release and Upload (only for tag events)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: openwrt-tr3000.zip

      - name: Delete workflow runs
        if: success()
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 3

      - name: Remove old Releases
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 10
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
